import { Service, Config } from "@cmmv/core";

@Service()
export class DeepSeekService {
    async generateContent(prompt: string) : Promise<string> {
        const deepseekApiKey = Config.get("blog.deepseekApiKey");

        const response = await fetch('https://api.deepseek.com/v1/chat/completions', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${deepseekApiKey || ''}`
            },
            body: JSON.stringify({
                model: "deepseek-chat",
                messages: [
                    {
                        role: "user",
                        content: prompt
                    }
                ],
                temperature: 0.1,
                top_p: 0.9,
                max_tokens: 8192
            })
        });

        if (!response.ok)
            throw new Error(`Failed to generate AI content: ${await response.text()}`);

        const deepseekResponse = await response.json();
        const generatedText = deepseekResponse.choices?.[0]?.message?.content;

        if (!generatedText)
            throw new Error('No content generated by DeepSeek');

        return generatedText;
    }
}
