import { Service, Config } from "@cmmv/core";

@Service()
export class GrokService {
    async generateContent(prompt: string) : Promise<string> {
        const grokApiKey = Config.get("blog.grokApiKey");

        const response = await fetch('https://api.grok.x/v1/chat/completions', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${grokApiKey || ''}`
            },
            body: JSON.stringify({
                model: "grok-2",
                messages: [
                    {
                        role: "user",
                        content: prompt
                    }
                ],
                temperature: 0.7,
                max_tokens: 8000
            })
        });

        if (!response.ok) {
            const error = await response.text();
            throw new Error(`Failed to generate AI content: ${response.statusText}`);
        }

        const grokResponse = await response.json();
        const generatedText = grokResponse.choices?.[0]?.message?.content;

        if (!generatedText)
            throw new Error('No content generated by Grok');

        return generatedText;
    }
}
